# the class labels we cant to detect
names: ["car"]
# number of classes to be detected
nc: 1

# where to store results
train: /ghome/group01/mcv-m6-2023-team2/week5/detections/train
val: /ghome/group01/mcv-m6-2023-team2/week5/detections/val