dataset_dir: ../data/aic19/train
path_results: ./detections/yolo
weights: weights/best.pt
store_results: true
num_frames: 99999999
sequences:
    - S01
    - S03
    - S04
cameras:
    S01:
        - c001
        - c002
        - c003
        - c004
        - c005
    S03:
        - c010
        - c011
        - c012
        - c013
        - c014
        - c015
    S04:
        - c016
        - c017
        - c018
        - c019
        - c020
        - c021
        - c022
        - c023
        - c024
        - c025
        - c026
        - c027
        - c028
        - c029
        - c030
        - c031
        - c032
        - c033
        - c034
        - c035
        - c036
        - c037
        - c038
        - c039
        - c040