path_tracking_data: ./data/trackers/mot_challenge/parabellum-train
tracking_type: kalman
path_results: ./tracking/results
dataset_dir: ../data/aic19/train
detections_dir: ./detections/yolo
filter_by_area: false
filter_area_threshold: 4800  # = 80px x 60px
filter_parked: false
filter_parked_threshold: 50  # px